export enum RequestTreatmentStatusEnum {
    "INITIATE" = "INITIATE",
    "EN_ATTENTE_TRAITEMENT" = "EN_ATTENTE_TRAITEMENT",
    "TRAITEMENT_ENCOURS" = "TRAITEMENT_ENCOURS",
    "TRAITEMENT_TERMINE" = "TRAITEMENT_TERMINE",
  }