
name: Angular build Pipeline

on:
  pull_request:
    branches:
      - master
      
jobs:
  web-deploy:
    name: Build Angular App
    runs-on: ubuntu-latest

    steps:
    - run: echo "Build project"
