
name: Angular build Pipeline

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    types:
      - opened
      
jobs:
  web-deploy:
    name: Build Angular App
    runs-on: ubuntu-latest

    steps:
    - name: Get latest code
      uses: actions/checkout@v2.3.2
