name: Angular CI/CD Pipeline

on: 
  pull_request:
    branches:
      - master
    types:
      - closed
      
jobs:
  web-deploy:
    if: github.event.pull_request.merged == true
    name: Build and Deploy Angular App
    runs-on: ubuntu-latest

    steps:
    - run: echo "This PR was approved"
