name: Angular CI/CD Pipeline

on: 
  pull_request_review:
    types:
      - submitted
      
jobs:
  web-deploy:
    if: github.event.review.state == 'approved'
    name: Build and Deploy Angular App
    runs-on: ubuntu-latest

    steps:
    - run: echo "This PR was approved"
